openapi: 3.0.3
info:
  title: Farragut Web Application API
  version: 1.0.0

paths:
  /company:
    get:
      x-spring-paginated: true
      summary: Get all companies
      operationId: getCompanies
      tags:
        - company
      description: Retrieves a paginated list of all companies.
      responses:
        200:
          description: A page of companies
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Page'

  /company/{id}:
    get:
      summary: Get company by ID
      operationId: getCompany
      tags:
        - company
      description: Retrieves detailed information about a specific company by its ID.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: The company requested
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Company"

components:
  schemas:
    Company:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: 'The company UUID as generated by the system.'
          example: '550e8400-e29b-41d4-a716-446655440000'
        name:
          type: string
          description: 'The company name.'
          example: 'Company A'
        year:
          type: integer
          description: 'The year the company was organized.'
          example: 2021

    Page:
      description: minimal Page object
      type: object
      properties:
        page:
          type: integer
        size:
          type: integer
