openapi: 3.0.3
info:
  title: Farragut Web Application API
  version: 1.0.0

paths:
  /company:
    get:
      #      x-spring-paginated: true
      summary: Get all companies
      operationId: getCompanies
      tags:
        - company
      description: Retrieves a paginated list of all companies.
      parameters:
        - in: query
          name: pageable
          required: false
          schema:
            $ref: '#/components/schemas/Pageable'
      responses:
        200:
          description: A page of companies
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Page'

  /company/{id}:
    get:
      summary: Get company by ID
      operationId: getCompany
      tags:
        - company
      description: Retrieves detailed information about a specific company by its ID.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: The company requested
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Company"

components:
  schemas:
    Company:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: 'The company UUID as generated by the system.'
          example: '550e8400-e29b-41d4-a716-446655440000'
        name:
          type: string
          description: 'The company name.'
          example: 'Company A'
        year:
          type: integer
          description: 'The year the company was organized.'
          example: 2021
        campId:
          type: string
          format: uuid
          description: 'The camp UUID as generated by the system.'
          example: '550e8400-e29b-41d4-a716-446655440005'

    Pageable:
      description: Minimal page object
      type: object
      properties:
        page:
          type: integer
        size:
          type: integer

    Page:
      description: Minimal page object
      type: object
      properties:
        page:
          type: integer
        size:
          type: integer
        totalPages:
          type: integer
        totalCount:
          type: integer
          format: int64
        values:
          type: array
          items:
            oneOf:
              - $ref: '#/components/schemas/Company'

    Person:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: 'The person UUID as generated by the system.'
          example: '550e8400-e29b-41d4-a716-446655440001'
        givenName:
          type: string
          description: 'The persons given name.'
          example: 'John'
        familyName:
          type: string
          description: 'The persons family name.'
          example: 'Doe'

    Photo:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: 'The photo UUID as generated by the system.'
          example: '550e8400-e29b-41d4-a716-446655440002'
        frontScanId:
          type: string
          format: uuid
          description: 'The front scan UUID as generated by the system.'
          example: '550e8400-e29b-41d4-a716-446655440003'
        backScanId:
          type: string
          format: uuid
          description: 'The back scan UUID as generated by the system.'
          example: '550e8400-e29b-41d4-a716-446655440004'

    Scan:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: 'The scan UUID as generated by the system.'
        file:
          type: string
          description: 'The file name of the scan.'
          example: 'scan.jpg'

    Camp:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: 'The camp UUID as generated by the system.'
          example: '550e8400-e29b-41d4-a716-446655440005'
        name:
          type: string
          description: 'The camp name.'
          example: 'Bennion'
