name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Analyze, Compile
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Fetch sources
        uses: actions/checkout@v4
